### ISSUE TITLE
War of Unifications CB is for a whole duchy at a time

### ISSUE THREAD

**Issue by jttheghost** [Rystic/ATLA-restored#186]
From Discord

**Comment by jttheghost** [comment]
This works as intended currently as the CB is for the dutchy. Is this too strong / needs to be reworked?

**Comment by tannerflick4** [comment]
I think you just have to see how fast you want Chin or his followers/religion to conquer. I prefer Cbs making vassals, because as a player this makes it a danger playing next to those religion followers, and while Chin was a great strategic mind his followers might not be like him as much.

Just like Alexander's heirs trying to claim his glory, to me.

There is my overthought comments on this :D

**Comment by TypicalCrusader** [comment]
Lets block the duchy one by age, and lets finally use offmap as a age changer as current one relies on some random water barony or county if i remeber correctly
